[config]
reload_apps = true
reload_gtk_theme = false
set_wallpaper = true
wallpaper_tool = 'Swww'
prefix = '@'
swww_options = [
    "--transition-type",
    "center",
]
run_after = [
  [ "echo", "'hello'" ]
]

[templates.name1]
input_path = "~/colors.css"
output_path = "~/.config/colors.css"