[config]
set_wallpaper = true
wallpaper_tool = 'Swww'
prefix = '@'
swww_options = [
    "--transition-type",
    "center",
]

[templates.name1]
input_path = "example/colors.css"
output_path = "example/a/colors-generated.css"